<?php


namespace JointApp\Views\User;


use JointApp\Views\SiteView\SiteView;

class SiteView_User_SignUp extends SiteView
{
    public bool $robotNoIndex = true;
    public bool $hasSignUpErrors = false;

    public bool $modalUserActive = true;

    public function handleViewParams(): void
    {
        parent::handleViewParams(); // TODO: Change the autogenerated stub

        if($this->u_isAuth){
            $this->modalUserActive = false;
        }
    }

    protected function replaceDefaultHeadLang()
    {
        $class_Name = 'JointApp\LangFiles\Views\User\SignUp\LangFiles_'.$this->ucfirstLang($this->userLang).'_V_U_SignUp_Head';
        return new $class_Name();
    }

    protected function replaceDefaultHeaderLang()
    {
        $class_Name = 'JointApp\LangFiles\Views\User\SignUp\LangFiles_'.$this->ucfirstLang($this->userLang).'_V_U_SignUp_Header';
        return new $class_Name();
    }

    public function putCustomTemplates(): void
    {
        $this->tpSet->SignUpTp = new TpView_User_SignUp();
    }
}