<?php


namespace JointApp\Views\User;


use JointApp\Views\SiteView\SiteView;

class SiteView_User_SignIn extends SiteView
{
    public bool $robotNoIndex = true;
    public bool $hasSignInErrors = false;

    public bool $modalUserActive = true;

    public function handleViewParams(): void
    {
        parent::handleViewParams(); // TODO: Change the autogenerated stub

        if($this->u_isAuth){
            $this->modalUserActive = false;
        }
    }

    public function putCustomTemplates(): void
    {
        $this->tpSet->SignInTp = new TpView_User_SignIn();
    }

    protected function replaceDefaultHeadLang()
    {
        $class_Name = 'JointApp\LangFiles\Views\User\SignIn\LangFiles_'.$this->ucfirstLang($this->userLang).'_V_U_SignIn_Head';
        return new $class_Name();
    }

    protected function replaceDefaultHeaderLang()
    {
        $class_Name = 'JointApp\LangFiles\Views\User\SignIn\LangFiles_'.$this->ucfirstLang($this->userLang).'_V_U_SignIn_Header';
        return new $class_Name();
    }
}