<?php


namespace Src\Views\Blog\IT;


use JointApp\Views\TpView;

class TpView_Blog_IT_FiftySqlQuestions extends TpView
{
    public $css=['fifty-sql-questions' => '/css/blog/fifty-sql-questions.css',];

    public function getDefaultLang()
    {
        $class_Name = 'Src\LangFiles\Views\Blog\Articles\FiftySqlQuestions\LangFiles_'.self::ucfirstLang($this->userLang).'_Views_B_A_FiftySqlQuestions';
        return new $class_Name();
    }

    public function getResponseHtml(): string
    {
        return '<article class="fifty-sql-questions">'.
        '<p>'.$this->langFile::P.'</p>'.
        '<ol>'.
        '<li>'.$this->langFile::Q1.
        '<ul>'.
        '<li>'.$this->langFile::A1.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q2.
        '<ul>'.
        '<li>'.$this->langFile::A2.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q3.
        '<ul>'.
        '<li>'.$this->langFile::A3.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q4.
        '<ul>'.
        '<li>'.$this->langFile::A4.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q5.
        '<ul>'.
        '<li>'.$this->langFile::A5.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q6.
        '<ul>'.
        '<li>'.$this->langFile::A6.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q7.
        '<ul>'.$this->langFile::A7.
        '<li>'.$this->langFile::A71.'</li>'.
        '<li>'.$this->langFile::A72.'</li>'.
        '<li>'.$this->langFile::A73.'</li>'.
        '<li>'.$this->langFile::A74.'</li>'.
        '<li>'.$this->langFile::A75.'</li>'.
        '<li>'.$this->langFile::A76.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q8.
        '<ul>'.
        '<li>'.$this->langFile::A8.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q9.
        '<ul>'.
        '<li>'.$this->langFile::A9.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q10.
        '<ul>'.
        '<li>'.$this->langFile::A10.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q11.
        '<ul>'.
        '<li>'.$this->langFile::A11.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q12.
        '<ul>'.
        '<li>'.$this->langFile::A12.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q13.
        '<ul>'.
        '<li>'.$this->langFile::A13.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q14.
        '<ul>'.$this->langFile::A14.
        '<li>'.$this->langFile::A141.'</li>'.
        '<li>'.$this->langFile::A142.'</li>'.
        '<li>'.$this->langFile::A143.'</li>'.
        '<li>'.$this->langFile::A144.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q15.
        '<ul>'.
        '<li>'.$this->langFile::A15.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q16.
        '<ul>'.
        '<li>'.$this->langFile::A16.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q17.
        '<ul>'.
        '<li>'.$this->langFile::A17.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q18.
        '<ul>'.
        '<li>'.$this->langFile::A18.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q19.
        '<ul>'.
        '<li>'.$this->langFile::Q19.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q20.
        '<ul>'.
        '<li>'.$this->langFile::A20.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q21.
        '<ul>'.
        '<li>'.$this->langFile::A21.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q22.
        '<ul>'.
        '<li>'.$this->langFile::A22.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q23.
        '<ul>'.
        '<li>'.$this->langFile::A23.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q24.
        '<ul>'.
        '<li>'.$this->langFile::A24.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q25.
        '<ul>'.
        '<li>'.$this->langFile::A25.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q26.
        '<ul>'.
        '<li>'.$this->langFile::A26.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q27.
        '<ul>'.
        '<li>'.$this->langFile::A27.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q28.
        '<ul>'.
        '<li>'.$this->langFile::A28.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q29.
        '<ul>'.
        '<li>'.$this->langFile::A29.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q30.
        '<ul>'.
        '<li>'.$this->langFile::A30.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q31.
        '<ul>'.
        '<li>'.$this->langFile::A31.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q32.
        '<ul>'.
        '<li>'.$this->langFile::A32.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q33.
        '<ul>'.
        '<li>'.$this->langFile::A33.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q34.
        '<ul>'.
        '<li>'.$this->langFile::A34.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q35.
        '<ul>'.
        '<li>'.$this->langFile::A35.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q36.
        '<ul>'.
        '<li>'.$this->langFile::A36.'</li>'.
        '</ul>'.
        '</li>'.
        '<li> '.$this->langFile::Q37.
        '<ul>'.
        '<li>'.$this->langFile::A37.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q38.
        '<ul>'.
        '<li>'.$this->langFile::A38.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q39.
        '<ul>'.
        '<li>'.$this->langFile::A39.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q40.
        '<ul>'.
        '<li>'.$this->langFile::A40.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q41.
        '<ul>'.
        '<li>'.$this->langFile::A41.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q42.
        '<ul>'.
        '<li>'.$this->langFile::A42.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q43.
        '<ul>'.
        '<li>'.$this->langFile::A43.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q44.
        '<ul>'.
        '<li>'.$this->langFile::A44.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q45.
        '<ul>'.
        '<li>'.$this->langFile::A45.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q46.
        '<ul>'.
        '<li>'.$this->langFile::A46.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q47.
        '<ul>'.
        '<li>'.$this->langFile::A47.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q48.
        '<ul>'.
        '<li>'.$this->langFile::A48.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q49.
        '<ul>'.
        '<li>'.$this->langFile::A49.'</li>'.
        '</ul>'.
        '</li>'.
        '<li>'.$this->langFile::Q50.
        '<ul>'.$this->langFile::A50.
        '<li>'.$this->langFile::A501.'</li>'.
        '<li>'.$this->langFile::A502.'</li>'.
        '<li>'.$this->langFile::A503.'</li>'.
        '<li>'.$this->langFile::A504.'</li>'.
        '<li>'.$this->langFile::A505.'</li>'.
        '</ul>'.
        '</li>'.
        '</ol>'.
        '</article>';
    }
}