<?php


namespace Src\Views\Blog\IT;


use Src\Views\Blog\View_Blog_Art;
use JointApp\Interfaces\LangWebViewInterface;


class View_Blog_IT_TestTaskPhpJob extends View_Blog_Art
{
    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $lang = 'LangFiles_' . self::langNs($viewLang) . '_Views_Blog_IT_TestTaskPhpJob';
        $loads[] = [$lang => $docRoot . '/LangFiles/Views/Blog/IT/' . $lang];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/blog/code-snippet.css',
        ]);
    }

    public static function printArtContent(\stdClass $langArtContent, \stdClass $viewParams, string $langLw): string
    {
        return '<section>'.

            '<h2>'.$langArtContent->analysis->h2.'</h2>'.
            '<p>'.$langArtContent->analysis->p1.'</p>'.
            '<div class="note">'.$langArtContent->analysis->note.'</div>'.
            '<p>'.$langArtContent->analysis->p2.'</p>'.
            '<p>'.$langArtContent->analysis->p3.
            '<ol>'.
            '<li>'.$langArtContent->analysis->li1.'</li>'.
            '<li>'.$langArtContent->analysis->li2.'</li>'.
            '<li>'.$langArtContent->analysis->li3.'</li>'.
            '</ol>'.
            '</p>'.
            '<p>'.$langArtContent->analysis->p4.'</p>'.
            '</section>'.
            '<section>'.
            '<h2>'.$langArtContent->docker->common->h2.'</h2>'.
            '<p>'.$langArtContent->docker->common->p1.'</p>'.
            '<p>'.$langArtContent->docker->common->p2.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>docker build . -t bookshop-test-1</li>'.
            '<li>docker run -d -p 8080:80 -p 3306:3306 --name bookshop-c-test-1 bookshop-test-1</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->docker->common->p3.'</p>'.
            '<div class="img-block">'.
            '<img src="/img/blog/testTaskPhpJob/img-1.png">'.
            '</div>'.
            '<p>'.$langArtContent->docker->common->p4.'</p>'.
            '<div class="img-block">'.
            '<img src="/img/blog/testTaskPhpJob/img-2.png">'.
            '</div>'.
            '<p>'.$langArtContent->docker->common->p5.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>/etc/init.d/mysql start</li>'.
            '<li>/etc/init.d/apache2 start</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<div class="img-block">'.
            '<img src="/img/blog/testTaskPhpJob/img-3.png">'.
            '</div>'.
            '<p>'.$langArtContent->docker->common->p6.
            '</p>'.
            '<section>'.
            '<h3>'.$langArtContent->docker->mc->h3.'</h3>'.
            '<p>'.$langArtContent->docker->mc->p1.'<div class="code-snippet">'.
            '<ul>'.
            '<li>apt-get install mc -y</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<div class="img-block">'.
            '<img src="/img/blog/testTaskPhpJob/img-4.png" style="max-width: 70%">'.
            '</div>'.
            '<p>'.$langArtContent->docker->mc->p2.'</p>'.
            '</section>'.
            '<section>'.
            '<h3>'.$langArtContent->docker->openSsh->h3.'</h3>'.
            '<p>'.$langArtContent->docker->openSsh->p1t1.' '.
            '<a href="https://www.warp.dev/terminus/ssh-docker-container" title="Writing a Dockerfile for an SSH
                server with password-based authentication">'.$langArtContent->docker->openSsh->p1ref.'</a>. '.
            $langArtContent->docker->openSsh->p1t2.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>RUN useradd -ms /bin/bash newuser</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->docker->openSsh->p2.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>docker build . -t bookshop-test-1</li>'.
            '<li>docker run -d -p 8080:80 -p 3306:3306 -p 2222:22 --name bookshop-c-test-1 bookshop-test-1</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<div class="img-block">'.
            '<img src="/img/blog/testTaskPhpJob/img-5.png">'.
            '</div>'.
            '<p>'.$langArtContent->docker->openSsh->p3.'</p>'.
            '<p>'.$langArtContent->docker->openSsh->p4.'</p>'.
            '<p>'.$langArtContent->docker->openSsh->p5.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>C:\Windows\System32\drivers\etc\hosts</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.
            'Добавим в него строчку'.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>127.0.0.1 bookshop.loc</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->docker->openSsh->p6.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>docker run -d -p 8080:80 -p 3306:3306 -p 2222:22 -h bookshop.loc --name bookshop-c-test-1 bookshop-test-1</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<div class="img-block">'.
            '<img src="/img/blog/testTaskPhpJob/img-6.png">'.
            '</div>'.
            '</section>'.
            '</section>'.
            '<section>'.
            '<h3>'.$langArtContent->docker->vh->h3.'</h3>'.
            '<p>'.$langArtContent->docker->vh->p1.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>ServerName bookshop.loc</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->docker->vh->p2.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>echo "ServerName localhost" >> /etc/apache2/apache2.conf</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.
            $langArtContent->docker->vh->p3.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>COPY /src /var/www/html/bookshop.loc</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->docker->vh->p4.'</p>'.
            '<div class="img-block">'.
            '<img src="/img/blog/testTaskPhpJob/img-7.png">'.
            '</div>'.
            '</section>'.
            '<section>'.
            '<h2>'.$langArtContent->scripts->h2.'</h2>'.
            '<p>'.$langArtContent->scripts->p.'</p>'.
            '<h3>'.$langArtContent->scripts->db->h3.'</h3>'.
            '<p>'.$langArtContent->scripts->db->p1.
            '<ol>'.
            '<li>'.$langArtContent->scripts->db->li1.'</li>'.
            '<li>'.$langArtContent->scripts->db->li2.'</li>'.
            '<li>'.$langArtContent->scripts->db->li3.'</li>'.
            '<li>'.$langArtContent->scripts->db->li4.'</li>'.
            '</ol>'.
            '</p>'.
            '<p>'.$langArtContent->scripts->db->p2.'</p>'.
            '<h3>'.$langArtContent->scripts->php->h3.'</h3>'.
            '<p>'.$langArtContent->scripts->php->p1.'</p>'.
            '<p>'.$langArtContent->scripts->php->p2.
            '<ul>'.
            '<li><b>'.$langArtContent->scripts->php->li1.'</b>'.
            '<ol>'.
            '<li>'.$langArtContent->scripts->php->li11.'</li>'.
            '<li>'.$langArtContent->scripts->php->li12.'</li>'.
            '<li>'.$langArtContent->scripts->php->li13.'</li>'.
            '</ol>'.
            '</li>'.
            '<li>'.$langArtContent->scripts->php->li2.
            '<ol>'.
            '<li>'.$langArtContent->scripts->php->li21.'</li>'.
            '<li>'.$langArtContent->scripts->php->li22.'</li>'.
            '</ol>'.
            '</li>'.
            '<li><b>js</b>-'.$langArtContent->scripts->php->li3.
            '<ol>'.
            '<li>googleapis.js - '.$langArtContent->scripts->php->li31.' jQuery</li>'.
            '<li>report.js - '.$langArtContent->scripts->php->li32.'</li>'.
            '</ol>'.
            '</li>'.
            '</ul>'.
            '</p>'.
            '<p>'.$langArtContent->scripts->php->p3.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>docker build . -t bookshop-test</li>'.
            '<li>docker run -d -p 8080:80 -p 3306:3306 -p 2222:22 -h bookshop.loc --name bookshop-c-test bookshop-test</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->scripts->php->p4.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>/etc/init.d/mysql start</li>'.
            '<li>/etc/init.d/apache2 start</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->scripts->php->p5.
            '<div class="img-block">'.
            '<img src="/img/blog/testTaskPhpJob/img-8.png">'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->scripts->php->p6.'</p>'.
            '</section>'.
            '<section>'.
            '<h2>'.$langArtContent->additional->h2.'</h2>'.
            '<p>'.$langArtContent->additional->p1.'</p>'.
            '<h3>'.$langArtContent->additional->h31.'</h3>'.
            '<p>'.$langArtContent->additional->p2.
            '<div class="code-snippet">'.
            '<ul>'.
            '<li>git remote add test-bookshop https://github.com/rightJoint/test-bookshop</li>'.
            '<li>git push test-bookshop bookshop</li>'.
            '</ul>'.
            '</div>'.
            '</p>'.
            '<p>'.$langArtContent->additional->p3.
            '<div class="img-block">'.
            '<img src="/img/blog/testTaskPhpJob/img-9.png" style="max-width: 70%">'.
            '</div>'.
            '</p>'.
            '<h3>'.$langArtContent->additional->h32.'</h3>'.
            '<p>'.$langArtContent->additional->p4.'</p>'.
            '<h3>'.$langArtContent->additional->h33.'</h3>'.
            '<p>'.$langArtContent->additional->p51.
            '<a href="https://forums.docker.com/t/apache2-not-start-in-docker-container/89363/2">forums.docker.com</a> и
            <a href="https://stackoverflow.com/questions/49764989/cannot-start-apache-automatically-with-docker">stackoverflow.com</a>,'.
            $langArtContent->additional->p52.
            '</p>'.
            '</section>';
    }
}