<?php


namespace JointApp\Controllers\Test;


use JointApp\Controllers\Records\RecordsControllerWeb;

class Controller_Test_Log extends RecordsControllerWeb
{
    public string $processUri = '/test/migrations/log';
    public string $list_frame_id = 'migrations_log';

    public function prepareSearchFields(): void
    {
        parent::prepareSearchFields(); // TODO: Change the autogenerated stub

        $this->searchFields['add_date']['search'] = 0;
        $this->searchFields['migration_log']['search'] = 0;
        $this->searchFields['migration_log']['sort'] = 0;

    }
}