<?php


namespace Src\Views\Blog;


use JointApp\Views\Records\RecordListView;
use JointApp\Views\SiteView\SiteView;

class SiteView_Blog_Art extends SiteView
{
    public string $logo = '/img/popimg/blog-logo.png';
    public string $shortcutIcon = '/img/popimg/blog-icon.png';

    const ART_COVERS = '/userdata/blog/covers';

    public $artRow = [];
    public $artTags = [];

    public string $commentP_id = '';
    public string $formCommentsContent = '';
    public string $formCommentsErr = '';
    public string $artRef = '';
    public array $listComments = [];
    public int $countComments = 0;

    public int $curPage = 1;
    public int $onPage = 10;

    public string $sort = 'new-first';
    public string $viewtype = 'tree';

    public static function loadLangView(string $docRoot = __DIR__, string $viewLang = 'ru', $loads = []): LangWebViewInterface
    {
        $lang = 'LangFiles_' . self::langNs($viewLang) . '_Views_BlogArts';
        $loads[] = [$lang => $docRoot . '/LangFiles/Views/Blog/' . $lang];
        return parent::loadLangView($docRoot, $viewLang, $loads);
    }

    public function addViewParams(callable $addViewParams)
    {
        parent::addViewParams($addViewParams); // TODO: Change the autogenerated stub
        $addParams = new \stdClass();
        $addParams->artRow = $this->artRow;
        $addParams->artTags = $this->artTags;
        $addParams->commentP_id = $this->commentP_id;
        $addParams->formCommentsContent = $this->formCommentsContent;
        $addParams->formCommentsErr = $this->formCommentsErr;
        $addParams->artRef = $this->artRef;
        $addParams->listComments = $this->listComments;
        $addParams->countComments = $this->countComments;
        $addParams->curPage = $this->curPage;
        $addParams->onPage = $this->onPage;
        $addParams->sort = $this->sort;
        $addParams->viewtype = $this->viewtype;

        $addViewParams($addParams);
    }

    function langHeaderUpdate(callable $updateFromArray): void
    {
        $updateFromArray(['h1' => $this->artRow['artName']]);
    }

    function langHeadUpdate(callable $updateFromArray): void
    {
        $updateFromArray([
                'title' => $this->artRow['artName'],
                'description' => $this->artRow['artMeta']]
        );
    }

    public static function addStyleLinks(callable $addStyleLinks): void
    {
        parent::addStyleLinks($addStyleLinks); // TODO: Change the autogenerated stub
        $addStyleLinks([
            '/css/blog/blogArts.css',
            '/css/blog/blogComment.css',
            '/css/blog/blogOptionsPanel.css',
        ]);
    }

    public static function addScriptLinks(callable $addScriptLinks): void
    {
        parent::addScriptLinks($addScriptLinks); // TODO: Change the autogenerated stub
        $addScriptLinks([
            '/lib/js/tinymce/js/tinymce/tinymce.min.js',
            '/js/blog/blog-comments.js',
        ]);
    }


    public static function createPageContent(\stdClass $langPageContent, \stdClass $viewParams): string
    {
        $fromParams = new \stdClass();
        $fromParams->formCommentsContent = $viewParams->formCommentsContent;
        $fromParams->commentP_id = $viewParams->commentP_id;
        $fromParams->formCommentsErr = $viewParams->formCommentsErr;
        $fromParams->artRef = $viewParams->artRef;

        $filterParams = new \stdClass();
        $filterParams->curPage = $viewParams->curPage;
        $filterParams->onPage = $viewParams->onPage;
        $filterParams->sort = $viewParams->sort;
        $filterParams->viewtype = $viewParams->viewtype;

        $artTags = '';

        for ($i=0; $i<count($viewParams->artTags); $i++){
            $artTags.='<span class="tag-value">'.$viewParams->artTags[$i].'</span>';
        }

        $pageContent =
            '<div class="contentBlock-frame"><div class="contentBlock-center">'.
            '<div class="contentBlock-wrap">'.
            '<div class="blog-container">'.
            '<div class="blog-header">'.
            '<div class="blog-header-meta"><h2>'.$viewParams->artRow['artMeta'].'</h2></div>'.
            '<div class="blog-header-img"><img src="'.self::ART_COVERS.'/'.$viewParams->artRow['artImg'].'"></div>'.
            '</div>'.
            '<div class="blog-info">'.
            '<div class="blog-info-dates">'.
            '<span class="b-em-container">'.$langPageContent->artHeader->created.':</span>'.
            '<span class="b-em-value">'.$viewParams->artRow['pubDate'].'</span>';
        if(!empty($viewParams->artRow['refreshDate'])){
            $pageContent.='<span class="b-em-container">'.$langPageContent->artHeader->refresh.':</span>'.
                '<span class="b-em-value">'.$viewParams->artRow['refreshDate'].'</span>';
        }
        $pageContent.='</div>'.
            '<div class="blog-info-tags">'.
            '<span class="b-em-container">'.$langPageContent->artHeader->tags.':</span>'.
            $artTags.'</div>'.
            '</div>'.
            '<div class="art-content">'.
            static::printArtContent($langPageContent->langArtContent, $viewParams, $langPageContent->langLw).
            '</div>'.
            '<div class="art-comments">';
        if(!$viewParams->artRow['commentsFlag']){
            $pageContent.='<h3>'.$langPageContent->commentsH3.'</h3>'.
            '<input type="hidden" id="blog-art-ref" value="'.$viewParams->artRef.'">'.
            static::printArtCommentsOptions($langPageContent->landFilter, $viewParams->countComments, $filterParams).
                self::printArtComments($langPageContent->formComments, $langPageContent->langList, $fromParams,
                    $viewParams->listComments, $filterParams);
        }else{
            $pageContent.= static::printArtNoCommentsOptions($langPageContent->noComments);
        }
        $pageContent.=
            '</div>'.
            '</div>'.
            '</div>'.
            '</div>'.
            '</div>';

        return $pageContent;
    }

    public static function printArtCommentsOptions(\stdClass $landFilter, int $countComments, \stdClass $filterParams):string
    {
        $return = '<div class="blog-options">'.
            '<div class="blog-count">'.
            '<label>'.$landFilter->labelFound.'</label><span id="blog-count-comments">'.$countComments.'</span>'.
            '</div>'.
            '<div class="blog-pagination">'.
            RecordListView::paginationPrint($landFilter->langPg, $countComments, $filterParams->curPage, $filterParams->onPage).
            '</div>'.

            '<div class="blog-sort">'.
            '<label for="art-comments-options-sort">'.$landFilter->labelSort.'</label>'.
            '<select id="art-comments-options-sort">';
        $selected='';
        if($filterParams->sort == 'by-date'){
            $selected = " selected";
        }
        $return .= '<option value="by-date"'.$selected.'>'.$landFilter->optByDate.'</option>';
        $selected='';
        if($filterParams->sort == 'new-first'){
            $selected = " selected";
        }
        $return .= '<option value="new-first"'.$selected.'>'.$landFilter->optNewTop.'</option>';
        $selected='';
        if($filterParams->sort == 'like-count'){
            $selected = " selected";
        }
        $return .= '<option value="like-count"'.$selected.' disabled>'.$landFilter->optLikePlus.'</option>';
        $selected='';
        if($filterParams->sort == 'dislike-count'){
            $selected = " selected";
        }
        $return .= '<option value="dislike-count"'.$selected.' disabled>'.$landFilter->optLikeMinus.'</option>'.
            '</select>'.
        '<label for="art-comments-options-onPage">'.$landFilter->labelOnPage.'</label>'.
        '<select id="art-comments-options-onPage">';
        $selected='';
        if($filterParams->onPage == 5){
            $selected = " selected";
        }
        $return .= '<option value=5'.$selected.'>5</option>';
        $selected='';
        if($filterParams->onPage == 10){
            $selected = " selected";
        }
        $return .= '<option value=10'.$selected.'>10</option>';
        $selected='';
        if($filterParams->onPage == 20){
            $selected = " selected";
        }
        $return .= '<option value=20'.$selected.'>20</option>'.
            '</select>'.
            '</div>'.
            '<div class="blog-view-options">'.
            '<label for="art-comments-options-type">'.$landFilter->labelViewType.'</label>'.
            '<select id="art-comments-options-type">';
        $selected='';
        if($filterParams->viewtype == 'list'){
            $selected = " selected";
        }
        $return .= '<option value="list"'.$selected.'>'.$landFilter->opTypeList.'</option>';
        $selected='';
        if($filterParams->viewtype == "tree"){
            $selected = " selected";
        }
        $return .= '<option value="tree"'.$selected.'>'.$landFilter->opTypeTree.'</option>'.
            '</select>'.
            '</div>'.
            '</div>';
        return $return;
    }

    public static function printArtComments(\stdClass $langForm, \stdClass $langList, \stdClass $fromParams,
                                            array $listComments, \stdClass $filterParams):string
    {
        $authUser = false;
        global $currentUser;
        if(!empty($currentUser->user_id)){
            $authUser = true;
        }

        $return = '<div class="art-comments-list">';
        if($filterParams->viewtype == 'tree'){
            $return .= self::printArtCommentsTree($langList, $listComments, $langForm, $fromParams, $filterParams, $authUser);
        }elseif ($filterParams->viewtype == 'list'){
            $return .= self::printArtCommentsList($langList, $listComments, $langForm, $fromParams, $filterParams, $authUser);
        }
        $return .= '</div>'.
            '<div class="art-comments-form">'.
            self::printArtCommentsForm($langForm, $fromParams, $filterParams);

        $newActive = '';
        if($fromParams->commentP_id != 'new'){
            $newActive = ' active';
        }

        $return .='<div class="art-comments-new'.$newActive.'">'.
            '<span class="respond-new" comment-id="new" id="art-comments-respond-new" onclick="commentRespond(this)">'.$langForm->artCommentNew.'</span>'.
            '</div>'.
            '</div>';
        return $return;
    }

    public static function printArtCommentsTree(\stdClass $langList, array $listComments,
                                                \stdClass $langForm, \stdClass $fromParams, \stdClass $filterParams, bool $authUser): string
    {
        $return = '';
        if(count($listComments)){
            foreach ($listComments as $cmN => $comment){
                $avatar = '';
                if(!empty($comment['photoLink'])){
                    if($comment['network'] == 'site'){
                        $avatar.= self::USER_AVATARS_DIR.'/'.$comment['photoLink'];
                    }else{
                        $avatar.= $comment['photoLink'];
                    }
                }else{
                    $avatar.= '/img/popimg/avatar-default.png';
                }

                $return .= '<div class="art-comment-container">'.
                    '<div class="art-comment-container-top">'.
                    '<div class="art-comment-container-user">'.
                    '<img src="'.$avatar.'">'.
                    '<span>'.$comment['accAlias'].'</span>'.
                    '</div>'.
                    '<div class="art-comment-container-like" style="visibility: hidden">'.
                    'like +/-'.
                    '</div>'.
                    '</div>'.
                    '<div class="art-comment-container-content">'.
                    $comment['content'].
                    '<div class="comment-date">'.$comment['addDate'].'</div>'.
                    '</div>'.
                    '<div class="art-comment-container-bottom">';
                if($authUser){
                    $return .='<span class="respond" comment-id="'.$comment['comment_id'].'" onclick="commentRespond(this)">'.
                        $langList->respLink.
                    '</span>';
                }

                if(count($comment['recCm'])){
                    $return .= '('.count($comment['recCm']).') '.$langList->respTest;
                }

                if($fromParams->commentP_id == $comment['comment_id']){
                    $blogForm = new Blog_Comments_Form($langForm, $fromParams, $filterParams);
                    $return .= $blogForm->printBlogForm($langForm->socialButtons);
                }

                $return .= '</div>';
                if(count($comment['recCm'])){
                    $return .= self::printArtCommentsTree($langList, $comment['recCm'], $langForm, $fromParams, $filterParams, $authUser);
                }

                $return .='</div>';
            }
        }else{
            $return .= '<div class="add-first-comment">'.$langList->firstComment.'</div>';
        }

        return $return;
    }

    public static function printArtCommentsForm(\stdClass $langForm, \stdClass $fromParams, \stdClass $filerParams): string
    {
        $return = '';
        if($fromParams->commentP_id == 'new'){
            $blogForm = new Blog_Comments_Form($langForm, $fromParams, $filerParams);
            $return = $blogForm->printBlogForm($langForm->socialButtons);
        }

        return $return;
    }

    public static function printArtContent(\stdClass $langArtContent, \stdClass $viewParams, string $langLw): string
    {
        return 'put-art-content-there';
    }

    public static function printArtCommentsList(\stdClass $langList, array $listComments,
                                                \stdClass $langForm, \stdClass $fromParams, \stdClass $filterParams, bool $authUser): string
    {
        $return = '';
        if(count($listComments)){
            foreach ($listComments as $cmN => $comment){
                $avatar = '';
                if(!empty($comment['photoLink'])){
                    if($comment['network'] == 'site'){
                        $avatar.= self::USER_AVATARS_DIR.'/'.$comment['photoLink'];
                    }else{
                        $avatar.= $comment['photoLink'];
                    }
                }else{
                    $avatar.= '/img/popimg/avatar-default.png';
                }

                $return .= '<div class="art-comment-container quote">'.
                    '<div class="art-comment-container-top">'.
                    '<div class="art-comment-container-user">'.
                    '<span class="quote-marker">'.$langList->quote.'</span>'.
                    '<img src="'.$avatar.'">'.
                    '<span>'.$comment['accAlias'].'</span>'.
                    '</div>'.
                    '<div class="art-comment-container-like" style="visibility: hidden">'.
                    'like +/-'.
                    '</div>'.
                    '</div>';

                if(count($comment['recCm'])){
                    $return .= self::printArtCommentsList($langList, $comment['recCm'], $langForm, $fromParams, $filterParams, $authUser);
                }

                $return .= '<div class="art-comment-container-content">'.
                    $comment['content'].
                    '<div class="comment-date">'.$comment['addDate'].'</div>'.
                    '</div>'.
                    '<div class="art-comment-container-bottom">';
                if($authUser){
                    $return .='<span class="respond" comment-id="'.$comment['comment_id'].'" onclick="commentRespond(this)">'.
                        $langList->respLink.
                        '</span>';
                }

                /*
                if(count($comment['recCm'])){
                    $return .= '('.count($comment['recCm']).') '.$langList->respTest;
                }
                */

                if($fromParams->commentP_id == $comment['comment_id']){
                    $blogForm = new Blog_Comments_Form($langForm, $fromParams, $filterParams);
                    $return .= $blogForm->printBlogForm($langForm->socialButtons);
                }

                $return .= '</div>';

                $return .='</div>';
            }
        }else{
            $return .= '<div class="add-first-comment">'.$langList->firstComment.'</div>';
        }

        return $return;
    }

    public static function printArtNoCommentsOptions(string $noCommentsText):string
    {
        return '<div class="no-comments">'.$noCommentsText.'</div>';
    }
}