<?php
namespace Src\Controllers\Blog;


use JointApp\Controllers\Controller;
use JointApp\Controllers\ControllerWeb;
use JointApp\JointAppQueryBuilder;
use Src\Views\Blog\TpView_Blog_Options;
use Src\Views\Blog\TpView_Blog_Table;

class Controller_Blog extends ControllerWeb
{

    public array $artsList = [];
    public int $blogCountArts = 0;

    public bool $filterFlag = false;

    public string $filterArtName = '';
    public int $curPage = 1;
    public string $sortField = 'pubDate';
    public string $sortOrder = 'DESC';
    public int $onPage = 4;
    public int $inRow = 2;

    ///
    public array $filterCats = [];

    /*
    public function loadLangController():string
    {
        parent::loadLangController();
        $name = 'LangFiles_'.$this->langNs.'_Controller_BlogMain';
        require_once $this->docRoot.'/LangFiles/Controllers/Blog/'.$name.'.php';
        return $name;
    }

    public function controllerFilterBody($bodyParams = []): void
    {
        parent::controllerFilterBody($bodyParams); // TODO: Change the autogenerated stub

        if(isset($bodyParams['filterBlog']) and $bodyParams['filterBlog']='y'){
            $this->filterFlag = true;
            if(isset($bodyParams['filterBlog']) and $bodyParams['filterBlog'] == 'y'){
                if(isset($bodyParams['blog-filter-cat']) and !empty($bodyParams['blog-filter-cat'])){
                    $this->filterCat = $bodyParams['blog-filter-cat'];
                }
                if(isset($bodyParams['blog-filter-artName']) and !empty($bodyParams['blog-filter-artName'])){
                    $this->filterArtName = $bodyParams['blog-filter-artName'];
                }
                if(isset($bodyParams['blog-cur-page']) and !empty($bodyParams['blog-cur-page'])){
                    if($bodyParams['blog-cur-page'] != 'undefined'){
                        $this->curPage = $bodyParams['blog-cur-page'];
                    }
                }
                if(isset($bodyParams['blog-sort-field']) and !empty($bodyParams['blog-sort-field'])){
                    $this->sortField = $bodyParams['blog-sort-field'];
                }
                if(isset($bodyParams['blog-sort-order']) and !empty($bodyParams['blog-sort-order'])){
                    $this->sortOrder = $bodyParams['blog-sort-order'];
                }
                if(isset($bodyParams['blog-on-page']) and !empty($bodyParams['blog-on-page'])){
                    $this->onPage = $bodyParams['blog-on-page'];
                }
                if(isset($bodyParams['blog-in-row']) and !empty($bodyParams['blog-in-row'])){
                    $this->inRow = $bodyParams['blog-in-row'];
                }
            }
        }
    }
    */

    private function blogFilterRequest()
    {
        if(isset($this->requestParams['blog-in-row']) and !empty($this->requestParams['blog-in-row'])){
            $this->inRow = $this->requestParams['blog-in-row'];
        }
        if(isset($this->requestParams['blog-on-page']) and !empty($this->requestParams['blog-on-page'])){
            $this->onPage = $this->requestParams['blog-on-page'];
        }
        if(isset($this->requestParams['blog-sort-order']) and !empty($this->requestParams['blog-sort-order'])){
            $this->sortOrder = $this->requestParams['blog-sort-order'];
        }
        if(isset($this->requestParams['blog-sort-field']) and !empty($this->requestParams['blog-sort-field'])){
            $this->sortField = $this->requestParams['blog-sort-field'];
        }
        if(isset($this->requestParams['blog-cur-page']) and !empty($this->requestParams['blog-cur-page'])){
            $this->curPage = $this->requestParams['blog-cur-page'];
        }
        if(isset($this->requestParams['blog-filter-artName']) and !empty($this->requestParams['blog-filter-artName'])){
            $this->filterArtName = $this->requestParams['blog-filter-artName'];
        }
        if(isset($this->requestParams['blog-filter-cat']) and !empty($this->requestParams['blog-filter-cat'])){
            $this->filterCat = $this->requestParams['blog-filter-cat'];
        }
    }

    public function actionIndex()
    {
        $this->blogFilterRequest();

        $qBuilder = $this->blogSearchQuery();
        $this->artsList = $this->model->listRecords($qBuilder);

        $qBuilderCount = clone $qBuilder;
        $qBuilderCount
            ->limit('')
            ->order('');

        $this->blogCountArts = $this->model->countRecords($qBuilderCount);
        $this->filterCats = $this->fillFilterCats();

    }

    public function blogSearchQuery():JointAppQueryBuilder
    {
        $qBuilder = new JointAppQueryBuilder();

        if(!empty($this->filterCat) and $this->filterCat!='all'){
            $qBuilder->where('artCat="'.$this->filterCat.'"');
        }

        if(!empty($qBuilder->where)){
            $qBuilder->where .= ' and activeFlag is true';
        }else{
            $qBuilder->where .= 'activeFlag is true';
        }

        if(!empty($this->filterArtName) and !empty($this->filterArtName)){
            $qBuilder->having('artName like("%'.$this->filterArtName.'%")');
        }
        $limit = (($this->curPage-1)*$this->onPage).", ".$this->onPage;
        $qBuilder->limit($limit);

        $qBuilder->order($this->sortField.' '.$this->sortOrder);

        return $qBuilder;
    }

    public function actionFilter()
    {
        $arr = [];
        $this->blogFilterRequest();


        // if($this->filterFlag){

        $qBuilder = $this->blogSearchQuery();
        $tpView_table = new TpView_Blog_Table();
        $tpView_table->setUpCustomLang($tpView_table->getDefaultLang());
        $tpView_table->artsList = $this->model->listRecords($qBuilder);
        $tpView_table->inRow = $this->inRow;

        $arr['listView'] = $tpView_table->getResponseHtml();

        $tpView_options = new TpView_Blog_Options();
        $tpView_options->setUpCustomLang($tpView_options->getDefaultLang());


        $qBuilderCount = clone $qBuilder;
        $qBuilderCount
            ->limit('')
            ->order('');


        $this->blogCountArts = $this->model->countRecords($qBuilderCount);

        $tpView_options->blogCountArts = $this->model->countRecords($qBuilderCount);
        $tpView_options->onPage = $this->onPage;
        $tpView_options->curPage = $this->curPage;

        $arr['blogCountArts'] = $tpView_options->blogCountArts;

        $arr['pg'] = $tpView_options->paginationPrint();
        // }

        $this->responseJson = $arr;
    }

    public function fillFilterCats():array
    {
        $return = ['all' => 'all categories'];
        $qBuilder = new JointAppQueryBuilder();
        $qBuilder->select('cat_id, catName_'.$this->userLang.' AS catName')
            ->from('blogCats')
            ->order('catName');
        if($res = $this->model->pdoQuery($qBuilder->buildQuery())){
            while ($row = $res->fetch(\PDO::FETCH_ASSOC)){
                $return[$row['cat_id']] = $row['catName'];
            }
        }

        return $return;
    }

}